/*
 * Copyright (c) 2006-2020, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2020-07-07     hanbo       the first version
 */
#include "drv_common.h"
#include <rtthread.h>
#include <rtdevice.h>
#include <board.h>
#include "drv_spi.h"
#include "spi_flash_sfud.h"

/* Set up SPI MOSI MISO CLK pin since
 *  rt_hw_spi_device_attach only sets CS pin*/
static void spi_pin_init(void)
{
    /* This code is generated by CubeMx*/

    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* USER CODE BEGIN SPI1_MspInit 0 */

    /* USER CODE END SPI1_MspInit 0 */
    /* Peripheral clock enable */
    __HAL_RCC_SPI1_CLK_ENABLE();

    __HAL_RCC_GPIOB_CLK_ENABLE();
    /**SPI1 GPIO Configuration
    PB3     ------> SPI1_SCK
    PB4     ------> SPI1_MISO
    PB5     ------> SPI1_MOSI
    */
    GPIO_InitStruct.Pin = GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF5_SPI1;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    /* SPI1 interrupt Init */
    HAL_NVIC_SetPriority(SPI1_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(SPI1_IRQn);
    /* USER CODE BEGIN SPI1_MspInit 1 */

    /* USER CODE END SPI1_MspInit 1 */
}

static int w25q_spi_device_init()
{
    rt_err_t ret;

    __HAL_RCC_GPIOB_CLK_ENABLE();
    spi_pin_init();
    if(RT_EOK == rt_hw_spi_device_attach("spi1", "spi10", GPIOB, GPIO_PIN_0)){
        /* probe spi10 as name W25Q16 to RT Kernel */
        if (NULL == rt_sfud_flash_probe("W25Q16", "spi10")) {
            rt_kprintf("spi flash probe failed!\n");
        }
    } else {
        rt_kprintf("Cannot attach spi device\n");
        ret = RT_ERROR;
    }

    return ret;
}

INIT_DEVICE_EXPORT(w25q_spi_device_init);
